<img style="float: left; margin: 30px 15px 15px 15px;" src="https://pngimage.net/wp-content/uploads/2018/06/logo-iteso-png-5.png" width="300" height="500" /> 
    
    
### <font color='navy'> Simulación de procesos financieros. 

**Nombres:** Gerardo Ruiz Velasco Lazalde y Dayana Navarro Valencia

**Fecha:** 10 de Febrero del 2020

**Expediente** : if721470 y 
**Profesor:** Oscar David Jaramillo Zuluaga.

**LINK DE GITHUB:**

# Tarea 2: Clase SPF

## Enunciado de tarea 
> # Tarea 2:

1. Imagine una rutina contable utilizada en una librería. Funciona en una lista con sublistas, que se ven así:
![imagen.png](attachment:imagen.png)
Escriba un programa en Python, que devuelve una lista con tuplas de tamaño 2. Cada tupla consiste en el número de pedido y el costo total del pedido. El producto debe aumentarse en 10€ si el valor de la orden es inferior a 100,00 €. 
Escribe un programa Python usando unicamente las funciones **lambda y map**.

`orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]`
           
2. La misma librería, pero esta vez trabajamos en una lista diferente. Las sublistas de nuestras listas se ven así: 
[número de orden, (número de artículo, cantidad, precio por unidad), ... (número de artículo, cantidad, precio por unidad)] 

`orders = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
	       [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
	       [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
           [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)] ]`

Escriba un programa que devuelva una lista de dos tuplas que tengan la información de (número de pedido, cantidad total de pedido). Utilice la función `Reduce`. Recuerde el precio del pedido del producto debe aumentarse en 10€ si el valor de la orden es inferior a 100,00 €.

3. Resolver los anteriores ejercicios usando pandas (DataFrame)



4. Use filter to eliminate all words that are shorter than 4 letters from a list of words
`list='the notion of a lambda function goes all the way back to the origin of computer science'`

5. Use filter to determine the percentage of Fahrenheit temperatures in a list are within the range 32 to 80

6. Use reduce to find the lower left corner (minimum x and minimum y value) for a list of point locations
> **Hint**: Explore the command `np.minimum.reduce` [link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ufunc.reduce.html)

### Ejercicio 1: Imagine una rutina contable utilizada en una librería. Funciona en una lista con sublistas, que se ven así:
![imagen.png](attachment:imagen.png)
Escriba un programa en Python, que devuelve una lista con tuplas de tamaño 2. Cada tupla consiste en el número de pedido y el costo total del pedido. El producto debe aumentarse en 10€ si el valor de la orden es inferior a 100,00 €. 
Escribe un programa Python usando unicamente las funciones **lambda y map**.

`orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]`

#### SOLUCIÓN GERARDO

In [4]:
# Código de solución 
from functools import reduce
import numpy as np
import pandas as pd
from pandas import DataFrame

In [5]:
orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]

In [6]:
l1=lambda x,  y:x*y
def increase(value):
    if value < 100:
        value  +=10
    return value
x= list(map(increase,[l1(orders[i][2],orders[i][3]) for i in np.arange(len(orders))]))
result1=list(map(lambda x,y:(x[0],y),orders,x))
result1


[('34587', 163.8),
 ('98762', 284.0),
 ('77226', 108.85000000000001),
 ('88112', 84.97)]

#### SOLUCIÓN DAYANA

In [ ]:
# Código de solución 
.
.
.
.



### Ejercicio 2: La misma librería, pero esta vez trabajamos en una lista diferente. Las sublistas de nuestras listas se ven así: 
[número de orden, (número de artículo, cantidad, precio por unidad), ... (número de artículo, cantidad, precio por unidad)] 

`orders = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
	       [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
	       [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
           [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)] ]`

Escriba un programa que devuelva una lista de dos tuplas que tengan la información de (número de pedido, cantidad total de pedido). Utilice la función `Reduce`. Recuerde el precio del pedido del producto debe aumentarse en 10€ si el valor de la orden es inferior a 100,00 €.



#### SOLUCIÓN GERARDO

In [10]:
# Código de solución 
orders2 = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
          [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
          [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
          [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)] ]

minimo = 100
total = list(map(lambda x: [x[0]] + list(map(lambda y: y[1]*y[2] 
                    if y[1]*y[2]>=minimo else y[1]*y[2] +10 , x[1:])), orders2))

total = list(map(lambda x: [x[0]] + \
                 [reduce(lambda a,b: a + b, x[1:])], total))

total

[[1, 688.3299999999999],
 [2, 504.46000000000004],
 [3, 374.79999999999995],
 [4, 502.57]]

#### SOLUCIÓN DAYANA

In [ ]:
# Código de solución 
.
.
.
.



### Ejercicio 3: Resolver los anteriores ejercicios usando pandas (DataFrame)

#### SOLUCIÓN GERARDO

In [19]:
# Código de solución 

df1=pd.DataFrame(columns=["Order number","Book Title and Author","Quantity","Price per Item"], data=orders)
res3_1=[(df1.iloc[:,-2]*df1.iloc[:,-1]).apply(lambda x: x if x>=100 else (x+10))]
#sol3_1=sol3_1.append(ej1.iloc[:,0])
res3_1=pd.DataFrame(res3_1)
res3_1=res3_1.append(df1.iloc[:,0])
print(res3_1.T)

#ejercicio 2
orders2 = [[1, "5464", 4, 9.99, "8274",18,12.99, "9744", 9, 44.95], 
           [2, "5464", 9, 9.99, "9744", 9, 44.95, 0,0,0],
           [3, "5464", 9, 9.99, "88112", 11, 24.99, 0,0,0],
           [4, "8732", 7, 11.99, "7733",11,18.99, "88112", 5, 39.95]]
df2=pd.DataFrame(orders2)

res3_2= [((df2.iloc[:,2]*df2.iloc[:,3])+(df2.iloc[:,5]*df2.iloc[:,6])+(df2.iloc[:,8]*df2.iloc[:,9])).apply(lambda x: x if x>=100 else (x+10))]
print(res3_2)


        0 Order number
0   163.8        34587
1     284        98762
2  108.85        77226
3   84.97        88112
[0    678.33
1    494.46
2    364.80
3    492.57
dtype: float64]


#### SOLUCIÓN DAYANA

In [ ]:
# Código de solución 
.
.
.
.




### Ejercicio 4:  Use filter to eliminate all words that are shorter than 4 letters from a list of words
`list='the notion of a lambda function goes all the way back to the origin of computer science'`

#### SOLUCIÓN GERARDO

In [4]:
# Código de solución 
lista1="the notion of a lambda function goes all the way back to the origin of computer science"
l1=lista1.split()
l1
r=list(filter(lambda x: len(x)>=4, l1))
print(r)





['notion', 'lambda', 'function', 'goes', 'back', 'origin', 'computer', 'science']


#### SOLUCIÓN DAYANA

In [1]:
# Código de solución 
list1=['the', 'notion', 'of', 'a', 'lambda', 'function', 'goes', 'all', 'the', 'way', 'back', 'to', 'the' ,'origin', 'of', 'computer', 'science']

shorter = list(filter(lambda x: x if len(x) >= 4 else None , list1))
shorter



['notion',
 'lambda',
 'function',
 'goes',
 'back',
 'origin',
 'computer',
 'science']

### Ejercicio 5: Use filter to determine the percentage of Fahrenheit temperatures in a list are within the range 32 to 80

#### SOLUCIÓN GERARDO

In [6]:
# Código de solución 
r=list(filter(lambda x: (32< x < 80) , temperatures))
porcentaje=(len(r)/len(list(temperatures)))

r, porcentaje*100

([35.97387961379455,
  63.211195349983264,
  73.90387696517755,
  36.982512376595906,
  68.75395211338406,
  45.86132066984196,
  36.58307493022292,
  56.322083650154724,
  33.9621930206693,
  45.29071317816652,
  74.86289938282341,
  66.51091382521807,
  46.831316244170544,
  44.55796498523391],
 46.666666666666664)

#### SOLUCIÓN DAYANA

In [5]:
import numpy as np
np.random.seed(55555)
temperatures = np.random.uniform(25,110,30)
print(temperatures)

[ 35.97387961  99.13294268  92.6178302   99.69549478  63.21119535
  73.90387697  95.50028838  99.21476553  36.98251238 101.45813729
 100.5917418   89.38159435  89.52156589  83.8084752   28.37990868
  68.75395211  45.86132067  36.58307493  56.32208365  33.96219302
  45.29071318  74.86289938  66.51091383  88.19316186  94.26635864
  46.83131624 109.60744472 109.68427993  44.55796499  92.84146259]


In [4]:
# Código de solución 
x= list(filter(lambda temp: temp if temp > 32 else None , temperatures))
y= list(filter(lambda temp: temp if temp < 80 else None , x))

print(y)




[35.97387961379455, 63.211195349983264, 73.90387696517755, 36.982512376595906, 68.75395211338406, 45.86132066984196, 36.58307493022292, 56.322083650154724, 33.9621930206693, 45.29071317816652, 74.86289938282341, 66.51091382521807, 46.831316244170544, 44.55796498523391]


### Ejercicio 6: Use reduce to find the lower left corner (minimum x and minimum y value) for a list of point locations
> **Hint**: Explore the command `np.minimum.reduce` [link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ufunc.reduce.html)

#### SOLUCIÓN GERARDO

In [10]:
# Código de solución 
result=np.minimum.reduce(point_xy)
print(result)
result

[0 2]


array([0, 2])

#### SOLUCIÓN DAYANA

In [8]:
# Código de solución 
np.random.seed(55555)
point_xy = np.random.randint(0,100,[30,2])
print(point_xy)



[[17 97]
 [22 33]
 [37 46]
 [57 28]
 [11 25]
 [14  2]
 [74 16]
 [12 37]
 [35 21]
 [66 65]
 [86 58]
 [67 81]
 [ 0 48]
 [28 66]
 [76 22]
 [46 47]
 [64  7]
 [88 94]
 [65 13]
 [75 89]
 [23 17]
 [36 63]
 [62 36]
 [64 17]
 [18 19]
 [88 41]
 [21 49]
 [98 36]
 [81 73]
 [62 90]]


In [6]:
np.minimum.reduce(point_xy)

array([0, 2])